// <auto-generated />
namespace Blog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FeedbackCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeedbackCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201406051611549_Feedback-Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
